### ISSUE TITLE
FEATURE: Hex values

### ISSUE THREAD

**Issue by aarondluke** [maeganjwilson/artnet-converter#39] opened 2019-12-20 20:43 UTC
It would be super helpful if there was a way to also display the Artnet address in Hex instead of just decimal. Many consoles, nodes, and other devices still require hex values.

**Comment by maeganjwilson** [comment] 2020-01-19 16:56
I'll look into adding this as a setting and see how much work this needs.

**Comment by maeganjwilson** [comment] 2020-01-19 16:57
Duplicate of #38. Closing this issue.

**Closed by maeganjwilson** 2020-01-19 16:57 UTC
Labels: duplicate
